openapi: 3.0.1
info:
  title: SpaceCats Marketplace API
  description: API for managing intergalactic products
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /api/items:
    get:
      summary: Retrieve all items
      operationId: fetchAllItems
      responses:
        '200':
          description: A list of items
    post:
      summary: Add a new item
      operationId: createItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              : '#/components/schemas/ItemRequestDTO'
      responses:
        '201':
          description: Item created successfully
  /api/items/{id}:
    get:
      summary: Get item by ID
      operationId: fetchItemById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item details
        '404':
          description: Item not found
    delete:
      summary: Delete item by ID
      operationId: removeItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Item deleted
        '404':
          description: Item not found
components:
  schemas:
    ItemRequestDTO:
      type: object
      properties:
        name:
          type: string
          description: Name of the item
        description:
          type: string
          description: Description of the item
        price:
          type: number
          format: double
          description: Price of the item
    ItemResponseDTO:
      type: object
      properties:
        id:
          type: string
          description: Unique ID of the item
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
